### ISSUE TITLE
Review and merge Gallery work from ADK

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1349]
The gallery in KPI is almost ready, but it requires a review and several UI fixes before it can be merged. 

@pmusaraj to do a review of the UI and frontend code. @dorey will then review the Python code and tests. This work will be done in a new branch under the current repository, and future ADK work can be committed there (this allows us to more easily retain only the file changes relevant to the gallery.)

**Comment by pmusaraj** [comment]
renaming questions in the form builder and then redeploying breaks the gallery in a strange way. Submitted photos prior to renaming the questions are still there, but shown without a grouping and each on one row. Submissions after the renaming are fine. In this screenshot, new submissions are above the red line, old ones below: 

![testing adk gallery kobotoolbox 2017-06-20 13-33-20](https://user-images.githubusercontent.com/368961/27347138-7e79ee7c-55bd-11e7-96be-6419839f9ae1.jpg)

**Comment by emilykferguson** [comment]
Missing Functionality:
- [ ] I'm not able to switch to group the photos by record
- [ ] Other photos for specified record

![image](https://user-images.githubusercontent.com/15673694/27546696-85e92a76-5a61-11e7-9d6c-971267cacc61.png)


UI updates:
- [ ] Question title Should be: Roboto normal, size 16px, color: #59636B 
![image](https://user-images.githubusercontent.com/15673694/27545722-8dd6ead2-5a5e-11e7-8c85-130bb91770a8.png)
- [ ] Number of images Should be: size: 14px, color: #414453 
![image](https://user-images.githubusercontent.com/15673694/27545746-a0a9675c-5a5e-11e7-8a56-b7c0deeeda5a.png)
- [ ] Width between photos should be 8px (it's 12px now)
- [ ] Search bar should say: "Filter by question" and should be a dropdown of the photo related questions
![image](https://user-images.githubusercontent.com/15673694/27545786-bf0d1e3c-5a5e-11e7-9ebc-2df42e8c37e0.png)
- [ ] Photo title font
![image](https://user-images.githubusercontent.com/15673694/27546738-a6cd9024-5a61-11e7-83e5-c4113a596629.png)
- [ ] Color of filter icon: #414453

**Comment by jnm** [comment]
@yahyazini, the [question renaming problem](https://github.com/kobotoolbox/kpi/issues/1349#issuecomment-309832776), as I was able to observe it, only occurs when the actual question name ("Data Column Name" in the form builder question settings UI) changes. This happens even if the user doesn't change it explicitly: if a question's data column name has never been set manually, the form builder automatically updates it when the user changes the question label/title. I opened another issue to discuss this behavior: https://github.com/kobotoolbox/kpi/issues/1358.

We need @preisman's back-end code to degrade gracefully when it cannot [find a question by name](https://github.com/kobotoolbox/kpi/blob/c7afc0752f54932d3eda4826a04e4115d9e20226/kpi/deployment_backends/kc_access/shadow_models.py#L176) in the [JSON of the XForm's current version](https://github.com/kobotoolbox/kpi/blob/c7afc0752f54932d3eda4826a04e4115d9e20226/kpi/deployment_backends/kc_access/shadow_models.py#L101). We should discuss different approaches to this (probably on a call), but at the very least, attachments from questions that have the same name should be grouped together—even if that name is no longer found in the XForm's JSON. Right now, the `attachments` endpoint splits them apart as if each attachment belonged to a different (and nameless) question.

**Comment by yahyazini** [comment]
@jnm, does it make sense to look up questions using the name in the first place?

**Comment by jnm** [comment]
@yahyazini, just to jot down what we talked about with @dorey this morning:
* Yes, looking up questions by `name` (or `$autoname` in the pre-deployment content) is fine.
* We should use formpack's [`get_fields_for_versions()`](https://github.com/kobotoolbox/formpack/blob/master/src/formpack/pack.py#L182) to look up question labels and ordering instead of relying on the XForm's JSON.
* I need to make a one-liner fix to `get_fields_for_versions()` [here](https://github.com/kobotoolbox/formpack/blob/1f096db6c738f1d87581555d56abc067cfd21c94/src/formpack/pack.py#L249).

**Comment by magicznyleszek** [comment]
The PR now needs to take into account https://github.com/kobotoolbox/kpi/pull/1959#issuecomment-443280902 and to fix merge conflicts and to possibly be updated to be built upon `two-databases`, as it will be merged after it.

**Comment by Ig-Rebollo** [comment]
@bufke @magicznyleszek here is the link to the [Figma file with the new designs](https://www.figma.com/file/oVn7gQ8TOd8FjrUvNTxvcN/New-Gallery?node-id=0%3A1) for the Gallery based on our conversation last week. 

You can also navigate through [the prototype](https://www.figma.com/proto/oVn7gQ8TOd8FjrUvNTxvcN/New-Gallery?page-id=0%3A1&node-id=12%3A2052&viewport=245%2C48%2C0.44&scaling=min-zoom&starting-point-node-id=2%3A1001), though a few screens are missing to save space and not overcrowd the workspace. You might find a few odd steps here and there, so feel free to ask any questions if something doesn't make sense. 

Note that I also included several functionalities we did not discuss. These are therefore not necessary for the MVP:
- Toggle between grid view and list view (for now all we need is grid view)
- Display submission number on hover in grid view. If complicated, feel free to ignore for MVP
- Filter by date. I tried to make it simple, if easy to include that would be fantastic, but there's no need to include it in the MVP if it can delay things too much.
- No need to include the download button yet
- Settings button includes 'order', but it may include more things in the future, such as thumbnail size. No need to worry about any of that right now.
- The expanded view includes two buttons, one for processing, one for opening submission. Opening submission is more important and it would be nice to have it for the MVP. Process will have to wait.

**Comment by Ig-Rebollo** [comment]
After the last conversation with @davereinhart, please be aware of the following modifications in the Figma file for the MVP:

Load more instead of pages: 
<img width="863" alt="image" src="https://user-images.githubusercontent.com/22472326/161147883-1dcb319b-357d-4189-a520-00da47c97ef3.png">

No need for toggle list/grid for now, or the display ## dropdown. Instead, we'll add a pretty heading for now: 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/22472326/161147945-d68917e8-15ac-4728-abaf-cf055a61eb12.png">

FYI @magicznyleszek @jnm
