### ISSUE TITLE
Use 2 databases connections in KPI prior to split `kpi` and `kc` databases.

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2155]
In order to upgrade `kpi` (and maybe `kc` too) to Django 2.x and Python3, we need to proceed by several steps. 
As per discussed with @jnm, `KobocatDeploymentBackend` should use its specific database connection to interact with `kc` PostgreSQL database to avoid conflict between different Django version & migrations.

**Comment by noliveleger** [comment]
**TODO**:
- [x] Use 2 different databases connections 
- [ ] Refactor `KobocatDeploymentBackend` and `KobocatDataProxyViewSetMixin` to use only one way to access `kc` data. 
- [ ] Modify `kobo-install` to support `KC_DATABASE_URL`
- [ ] Modify `kobo-docker` (`kobo-install` branch) to support `KC_DATABASE_URL`.
- [ ] Apply those modifications to `OCHA` and `HHI` branches of `kobo-deployments` repository (after PR review and approval of #2155)
