### ISSUE TITLE
Add the audit meta question type to the formbuilder

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2187]
## Description

`audit` is supported in xlsform and pyxform, so it should be added to the formbuilder as well. 

See http://support.kobotoolbox.org/creating-forms/audit-logging-meta-question-type

**Comment by tinok** [comment]
@magicznyleszek Here is a mockup of how this could be added to the form settings: 
![image](https://user-images.githubusercontent.com/673511/65260278-23335780-dad4-11e9-93b8-12c5ddfec5bd.png)

This should include: 

- [ ] User can see and tick the audit checkbox
- [ ] (If the audit checkbox is ticked) show a text field to allow user to enter optional settings text
- [ ] Show help button along with label, pointing to [this page](http://support.kobotoolbox.org/creating-forms/audit-logging-meta-question-type)
- [ ] If ticked, and if text is entered, they should go into the form (see below)
- [ ] If a form is imported with audit meta question, make sure this is ticked in the formbuilder and any text from the appearance column is shown in the text field (sample form: [audit.xlsx](https://github.com/kobotoolbox/kpi/files/3632191/audit.xlsx))


type | name | appearance
--|--|--
audit|audit|[whatever text the user has entered]

For details on the feature and implementation in XLSForm see [here](https://docs.opendatakit.org/form-audit-log/).

**Comment by jnm** [comment]
Closed by #2429
