### ISSUE TITLE
[Public Collections] Feature polishing feedback

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2824]
## Description

- [x] disallow making empty collections public (hint: add children check to `assetUtils.isAssetPublicReady` function)
- [x] reset filters button for table is not needed
- [x] move number of children (out from next to name) to a separate column
- [x] the number of children is sometimes wrong `The number in the grey circle (child assets) is wrong, at least sometimes: tinokreutzer's 'Sample Library Blocks' has 60 assets, but in the table's grey circle it says '1'. This is also in the JSON for the search result. Whereas the children count of the asset itself is reliably 60.`
- [x] don't display all columns for My Library `The columns in the Public Collections view are not needed in the main library view since questions and blocks can't have an Organization, Primary Sector, or Country attached to them. This means these rows are almost always empty; only public collections or templates would have this information, but it's not a good use of space to show this in the main library view`
- [x] similarly to above `Sector, Country, and Organization are not needed in the single question block view since there is no way to specify this information`
- [x] Search in library view is not applied to questions and blocks Search terms are only added to the Collections query, not the `asset_type:question OR asset_type:block`
- [x] "Back" button is misaligned on asset page (Chrome?)
- [x] searching for a question inside a collection - is it possible from My Library?
- [x] fix unnecessary search calls (jnm edit: detailed at #2808?)

- [ ] ~~fix filtering: `It works to filter for "Central African Republic" but when I filter by organization (UNDP CAR) or Primary Sector (Economic/Social development) I get 0 results. Expected: I should get the same result each time`~~ moved to https://github.com/kobotoolbox/kpi/issues/2835
- [x] ~~Cloning an asset from a subscribed Collection causes 400/500 errors~~ :bug: moved to https://github.com/kobotoolbox/kpi/issues/2836
- [ ] ~~Collection content is displaying only 10 items~~ :bug: moved to https://github.com/kobotoolbox/kpi/issues/2834
- [x] ~~You can't add subscribed collection items in Form Builder~~ :bug: moved to https://github.com/kobotoolbox/kpi/issues/2832
- [x] ~~Fix search~~ :bug: moved to https://github.com/kobotoolbox/kpi/issues/2814

**Comment by jnm** [comment]
@magicznyleszek, this is ready to close, right?
