### ISSUE TITLE
 Public Collections: formbuilder library sidebar does not display any assets for subscribed collections

### ISSUE THREAD

**Issue by duvld** [kobotoolbox/kpi#2832]
## Tasks (jnm edit)

- [x] Add a failing unit test
- [x] Apply patch in [comment below](#issuecomment-708168429)
- [x] If results look weird, inspect the queries sent by the front end. For example, after applying this change, the library list will start showing the children of all subscribed collections because `asset_type:question OR asset_type:block OR asset_type:template OR asset_type:collection AND parent:null` is not the same as `(asset_type:question OR asset_type:block OR asset_type:template OR asset_type:collection) AND parent:null` ([see internal discussion](https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Public.20Collection.20feedback/near/1989) about parentheses) -- fixed on https://github.com/kobotoolbox/kpi/commit/2cde8d30eb35ba3e656c2bdbb96ec1ee0f2217c4

Once a PR is prepared, let's remember to deploy it on `kf.beta` and check for performance problems.

## Description

Mentioned in #2824, a subscribed collection's assets do not load into "Add from Library" sidebar in the formbuilder.

## Steps to Reproduce
(In public collections https://kf.beta.kbtdev.org)
1. Subscribe to a Public Collection that contains assets
2. Open the formbuilder and open the "Add from Library" sidebar
3. Click on "Select Collection Name"
4. Select subscribed collection

## Expected behavior 

List of the assets from the subscribed collection appears below dropdown

## Actual behavior 

Returns "No search results found" and "0 assets found"

## Additional details

@jnm found the following wrt this issue:
> impossible to see subscribed collection contents in the form builder's library sidebar (because the `parent__uid` query is returning nothing; [read more here](https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Public.20Collection.20optimizations/near/861))
>  - but, you may wonder, how does the collection detail view in the library show the children? answer: it gets the list of children directly from the asset detail endpoint

Contents of `read more here`:

>i think it is a Good Idea™ to include only subscribed assets, and not their children, in the asset list results. some of these collection assets can have thousands of children, and there's no way we want all of those being returned all the time
>i.e. i'm happy with the change of behavior from the code in `master`
>
>The caveat is that we need a query like `https://kf.beta.kbtdev.org/api/v2/assets/?q=parent__uid:aUYhcQARSEe7Nh24xqxj6q` to work, where `aUYhcQARSEe7Nh24xqxj6q` is a subscribed collection. Right now, it returns nothing

**Comment by jnm** [comment]
**Read Me First:** after I wrote everything below, I realized that the kind of search provided by `/api/v2/assets/[collection uid]/children?q=temperature` will be pretty dissatisfying. As a user, I'd like to search for a keyword like "temperature" without having to remember (or even pick) a collection beforehand.

(old stuff below)

Hey @.duvld, @.noliveleger and I discussed this and considered the following solutions, none of which we liked:
1. changing [`KpiObjectPermissionsFilter.filter_queryset()`](https://github.com/kobotoolbox/kpi/blob/a0d8104d5295997b94df2415e7ac50f678b132cb/kpi/filters.py#L76) back to the [old behavior](https://github.com/kobotoolbox/kpi/blob/46c8086438ee1ade1deb4a66c73383a7327d261a/kpi/filters.py#L98-L106) of including all children of subscribed collections
2. adding some kludgy parameter to `/api/v2/assets` that would control whether or not children of subscribed collections are included
3. shoehorning in a way to filter (search) the `children` that are returned by `/api/v2/assets/[collection uid]`

Instead, we favor adding a new endpoint, `/api/v2/assets/[collection uid]/children`, that would essentially take the `children` already nested within the `/api/v2/assets/[collection uid]/` detail endpoint and return them at the top level:
```javascript
{
  "count": …,
  "next": …,
  "previous": …,
  "results": [
    /* a child of [collection uid] */
    /* another child of [collection uid] */
    …
  ]
}
```

It would then (to me, anyway!) make intuitive sense to search these children with a query like `/api/v2/assets/[collection uid]/children?q=temperature`.

**Comment by jnm** [comment]
@duvld, let's go with this approach:

```diff
diff --git a/kpi/filters.py b/kpi/filters.py
index 40c7d7f5..cdd14eb4 100644
--- a/kpi/filters.py
+++ b/kpi/filters.py
@@ -73,7 +73,11 @@ class KpiObjectPermissionsFilter:
 
         subscribed = self._get_subscribed(user)
 
-        return queryset.filter(pk__in=owned_and_explicit_shared.union(subscribed))
+        return queryset.filter(
+            pk__in=owned_and_explicit_shared.union(subscribed).union(
+                queryset.filter(parent__in=subscribed).values('pk')
+            )
+        )
 
     def _get_discoverable(self, queryset):
         # We were asked not to consider subscriptions; return all
```

I'm adding a checklist to the issue description now.

**Comment by jnm** [comment]
Fixed by #2841
