### ISSUE TITLE
Customizable account metadata

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3554]
We need to allow superusers to customize the fields (Sector, Country, etc.) in account-level metadata. For example, as a superuser, I want to make the Sector and Country fields mandatory, ~~and I want to add a new field called Region.~~

This affects the user registration screen:
![image](https://user-images.githubusercontent.com/2085013/142027468-d151f375-8681-4c4e-9914-d948aa332a32.png)

…and the account settings screen:
![image](https://user-images.githubusercontent.com/2085013/142028247-05a32b64-3105-4061-9bd6-743221189b57.png)

- [ ] Back-end work (Django Constance; `/environment/` API)  - #3555
- [ ] Registration screen work - #3556
- [ ] Account settings screen work - #3557

**Comment by magicznyleszek** [comment]
Note to developer: try using react-jsonschema with custom inputs: https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/#customizing-the-default-fields-and-widgets

**Comment by magicznyleszek** [comment]
Things to be fixed by @magicznyleszek :
- [ ] When trying to save a project's settings screen I get a toast message that I'm missing the sector, but the sector field (as well as country, operational purpose, and personally identifiable information) are not mentioned. I would expect that we do the same as in the user profile (highlight them all as red).
- [ ] Maybe we should also bring all error messages up together in the toast rather than just the first missing field? (Only when I specify a sector do I get "Please specify at least one country for your project") -- my preferred approach would be the "some fields have errors" (single) alertify message combined with red validation errors next to each field (as done in the user metadata) -- Agree, that seems much more user friendly. -- Ideally personal info should be in a different row than operational purpose, though this might not be a big deal now. 
- [ ] Very small issue, but should the personally identifiable information selector not be on the same line as the operational purpose of data? -- no preference here
- [ ] In the user profile there is a new tab "Security" which shows only "TBD Security" and a Data storage tab that shows "TBD Usage dash" :lol: -- I think we can wait. This would only help with the Security tab; the Data storage tab should still be removed, right?
- [ ] Also the introductory sentence should reflect that there are more fields now, so instead of Please specify the country and the sector where this project will be deployed, it should be something like Please specify country, sector, purpose and type of data for this project
- [ ] Finally, I find a bit inconsistent the font size of the 'select...' text in the dropdowns. The description text in the text boxes (i.e. Enter title of project here) is much bigger. I feel the 'Selects' should be the same size and font style or similar. I also noticed a similar problem in the account settings, here the select is kind of duplicated for 'Primary sector' Ignacio: I'd say the 'Select...' should simply look like the description below, maybe even be the description itself, so it can be removed from below, and there's no duplication -- Can we also drop "Select the primary sector in which you work"? -- Yes and yes!
- [ ] There's some odd difference in the validation error sizing here
