### ISSUE TITLE
[NLP] UX/UI fixes to front end (version in kvar)

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3567]
### In Table View
- [x] Question: How are the sizes of the modal determined? Could/should we make them more consistent?
- [x] In some cases scroll appears for images. See screenshot for example, if size of modal is not always the same, shouldn't the modal adapt to the size of the pictures? Alternatively, if the modal can't adapt, I would suggest to reduce the size of the image to fit it in the max width/height of the modal.
![image](https://user-images.githubusercontent.com/22472326/143242768-86b4b26f-1f3e-43dc-b67d-e8eb0d730491.png)
- [x] In audio modal, time takes a while to appear, so bar appears higher than it should for a while (see screenshot). It would be better if the whole audio component waited to load when the time is ready, so the whole thing loads simultaneously. 
![image](https://user-images.githubusercontent.com/22472326/143243149-b84cc197-ddeb-4010-b6e0-e172e2c48aa9.png)
- [x] Both pictures and the audio component can take a bit to load. We should add a loading icon/animation while they are loading. 
![image](https://user-images.githubusercontent.com/22472326/143243272-f5988ff1-8e88-4273-aacd-d331ccd6d1a8.png)
- [x] Play icon should be smaller (though grey background on hover should remain the size it is now - so smaller icon in the same hover area) 
![image](https://user-images.githubusercontent.com/22472326/143243323-dff15f91-8e8c-4891-ad88-2b56eb774a00.png)
- ~~Once transcripts or translations are saved, they should be added as new columns to the table view. For MVP, no special treatment at all. Just new columns to the right of the audio they came from.~~ duplicate of #3382

### In Single Processing View
- [x] Some text already appears in transcriptions and translations by default. This makes it difficult to test how it would feel in a real situation. Can we remove the default texts?
- [x] When a transcript/translation I just typed is saved (clicking the 'save' button) the editor should lock again, showing the trash can, pen icon, etc. but instead it simply greys out 'save', and forces me to click on 'back'. This is really strange, it should simply take me back when I click 'save'.
- [x] List of languages seems too small and crammed. Can we increase the font size to 14px?
![image](https://user-images.githubusercontent.com/22472326/143245061-a0f8f0a1-2074-4cbc-86aa-aa57c50fb4f4.png)
- [x] It would also be nice to increase the space between the columns so they spread nicer over the available area: 
![image](https://user-images.githubusercontent.com/22472326/143245506-13ba31f6-8b9b-4c0d-9c4c-55e3801542ae.png)
- [x] Also a bit of separation between rows would make it nicer: 
![image](https://user-images.githubusercontent.com/22472326/143245753-6c7173ab-62f7-4912-bab3-019f211f71bc.png)
- [x] Background grey colour is too strong, should be bluish grey from mockups (also in the Figma colours file): #F1F4FC
- [x] Underline indicating the page (transcripts, translations or coding) should always be the same width (50px), centered and smaller than the text. 
![image](https://user-images.githubusercontent.com/22472326/143246838-69b3d436-445e-4628-a1f5-e0d62dc15190.png)
- [x] Header should be updated to latest version. For this go to issue #3570
- [x] Dropdown for languages should be the blue option from the new dropdown component. Go to issue #3568 for more details
- [x] 'Modified November...' should use the next lighter grey in our system, have less weight, and be right next to the language dropdown. It should also say 'last modified ...'
- [ ] #3617
![image](https://user-images.githubusercontent.com/22472326/143268860-09284287-14c9-423d-872b-6b1466250e8d.png)
- [ ] Reduce the options on the top left corner of the audio to 'Display' and 'Settings'. Go to #3569 for more info.
- [x] For the time being, let's remove groups from the submission information on the side. We'll have to figure out how to display them later on, but for now I think just showing the questions is better.

### In Downloads
Downloads should be done in the downloads section. Issue for this here (to be created)

**Comment by magicznyleszek** [comment]
Note the `kvar` version is 2ec9d3516

**Comment by magicznyleszek** [comment]
All is done here, the two items unfinished were moved to their separate issues
