### ISSUE TITLE
UI Feedback -- Reports

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#858]
Cosmetic changes:
- [x] Take out all bold font and replace with Roboto Regular [Form, Data, Settings, graph settings, etc and also the warning and the graphs/charts cards (question name and type)]
- [x] Question Name should be Roboto Regular 16, Type is Roboto Regular 11.
- [x] Form name in Header is Roboto Regular 16.
- [x] Source and Help is Roboto Regular 13.
- [x] Color for side nav text is: #5C676E
- [x] Expand button should align between the user name and user photo.
- [x] Reduce the Form/Data/Settings Nav to be 66% of the header size.
- [x] Add 0.01% padding on the right side of the page.
- [x] "Projects" in the side nav is Roboto Regular 18, #8A9AA4
- [x] Deployed/Draft/Archived group names and all form names should be #5C676E

Behavior:
- [x] Add hovers for "Print" and "Expand".
- [ ] When user expands "Deployed", "Drafts", "Archived",  use the same behavior as Drive: 'Source' and 'Help' gets pushed down (doesn't need to be sticky) and 1 overall scroll bar appears.
