### ISSUE TITLE
Sharing Modal update checklist

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#902]
- [x] "Sharing Permissions" should be: Roboto Regular, Size 18, Color: #2196F3
- [x] Text input fields should have a line thickness of 1
- [x] "Invite people and specify access rights" should be: Roboto Regular, Size 14, Color: #4A4A4A
- [ ] Add "Done" button in bottom right corner.
![image](https://cloud.githubusercontent.com/assets/15673694/18095668/a21d73e4-6ea5-11e6-8066-1ccdd348faee.png)

- [x] Take out "Link Sharing" header and "Anyone with link can view" and replace with "Link to share".  Roboto Regular 14, #4A4A4A
- [x] Add left-aligned header above list of usernames, "Who has access". Roboto Regular 14, #4A4A4A
